-- 코드를 작성해주세요
WITH TEMP AS (
SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS MAX_SIZE
FROM ECOLI_DATA
GROUP BY YEAR(DIFFERENTIATION_DATE)
)

SELECT YEAR(A.DIFFERENTIATION_DATE) YEAR, (TEMP.MAX_SIZE - A.SIZE_OF_COLONY) YEAR_DEV, ID
FROM ECOLI_DATA A JOIN TEMP ON YEAR(A.DIFFERENTIATION_DATE) = TEMP.YEAR
WHERE YEAR(A.DIFFERENTIATION_DATE) = TEMP.YEAR
ORDER BY YEAR, YEAR_DEV