-- 코드를 입력하세요
# 경제 카테고리의 도서 id, 저자명, 출판일 출력
SELECT A.BOOK_ID, B.AUTHOR_NAME, DATE_FORMAT(A.PUBLISHED_DATE, '%Y-%m-%d') as PUBLISHED_DATE
FROM BOOK A JOIN AUTHOR B
ON A.AUTHOR_ID = B.AUTHOR_ID
WHERE A.CATEGORY = "경제"
ORDER BY A.PUBLISHED_DATE ASC